/**
 * Central asset module – all image/SVG imports live here.
 *
 * How to add a new asset:
 *   export { default as MY_ICON } from './assets/my-icon.svg'
 *
 * Then import it in any component:
 *   import { MY_ICON } from '../assets'
 */

export { default as LOGO } from './assets/logo.svg'
export { default as BACK_ARROW } from './assets/back-arrow.svg'

export { default as CAROUSEL_1 } from './assets/carousel/landscape-1.jpg'
export { default as CAROUSEL_2 } from './assets/carousel/landscape-2.jpg'
export { default as CAROUSEL_3 } from './assets/carousel/landscape-3.jpg'
export { default as CAROUSEL_4 } from './assets/carousel/landscape-4.jpg'
export { default as CAROUSEL_5 } from './assets/carousel/landscape-5.jpg'
export { default as CAROUSEL_6 } from './assets/carousel/landscape-6.jpg'
export { default as CAROUSEL_7 } from './assets/carousel/landscape-7.jpg'
export { default as CAROUSEL_8 } from './assets/carousel/landscape-8.jpg'
export { default as CAROUSEL_9 } from './assets/carousel/landscape-9.jpg'
export { default as CAROUSEL_10 } from './assets/carousel/landscape-10.jpg'
export { default as CAROUSEL_11 } from './assets/carousel/landscape-11.jpg'
export { default as CAROUSEL_12 } from './assets/carousel/landscape-12.jpg'
export { default as HERO_LOGO } from './assets/desktoplogo.gif'
export { default as HERO_LOGO_MOBILE } from './assets/mobilelogo.gif'
export { default as HERO_LOGO_STILL } from './assets/hero-logo.jpg'
export { default as LOGO_SHAPES } from './assets/logo-shapes.png'
export { default as PROJECT_ART } from './assets/project-art.png'
export { default as BOTANICAL_RESEARCH } from './assets/ux-ui/research-insights.png'
export { default as BOTANICAL_PERSONA_PHOTO } from './assets/ux-ui/persona-matthias.jpg'
export { default as BOTANICAL_PERSONA_SCENE } from './assets/ux-ui/persona-greenhouse.jpg'
export { default as BOTANICAL_STORYTELLING } from './assets/ux-ui/storytelling.jpg'
export { default as BOTANICAL_BUTTERFLY } from './assets/ux-ui/botanical-butterfly.svg'
export { default as BOTANICAL_PURPOSE } from './assets/ux-ui/purpose.png'
export { default as BOTANICAL_SCIENTIST } from './assets/ux-ui/botanical-scientist.svg'
export { default as BOTANICAL_PRINCIPLES } from './assets/ux-ui/principles.png'
export { default as BOTANICAL_OOUX } from './assets/ux-ui/ooux.png'
export { default as BOTANICAL_COVER } from './assets/ux-ui/botanical-cover.png'
export { default as YOGA_COVER } from './assets/ux-ui/yoga-cover.png'
export { default as DIGITAL_SOLUTIONS_COVER } from './assets/ux-ui/digital-solutions-cover.png'
export { default as DIGITAL_YOGA_COVER } from './assets/ux-ui/digital-yoga-cover.jpg'
export { default as DIGITAL_YOGA_SITEMAP } from './assets/ux-ui/digital-yoga-sitemap.jpg'
export { default as DIGITAL_YOGA_STYLE_TILE } from './assets/ux-ui/digital-yoga-style-tile.jpg'
export { default as DIGITAL_YOGA_WIREFRAMES } from './assets/ux-ui/digital-yoga-wireframes.jpg'
export { default as DIGITAL_YOGA_MOODBOARD } from './assets/ux-ui/digital-yoga-moodboard.jpg'
export { default as DIGITAL_YOGA_HIFI_TESTING } from './assets/ux-ui/digital-yoga-hifi-testing.png'
export { default as DIGITAL_YOGA_CONTENT_CREATION } from './assets/ux-ui/digital-yoga-content-creation.png'
export { default as DIGITAL_CPHFW_COVER } from './assets/ux-ui/digital-cphfw-cover.png'
export { default as DIGITAL_CPHFW_SITEMAP } from './assets/ux-ui/digital-cphfw-sitemap.png'
export { default as DIGITAL_CPHFW_MOODBOARD } from './assets/ux-ui/digital-cphfw-moodboard.png'
export { default as DIGITAL_CPHFW_STYLE_TILE } from './assets/ux-ui/digital-cphfw-style-tile.png'
export { default as DIGITAL_CPHFW_WIREFRAMES_BRANDS } from './assets/ux-ui/digital-cphfw-wireframes-brands.png'
export { default as DIGITAL_CPHFW_WIREFRAMES_EVENTS } from './assets/ux-ui/digital-cphfw-wireframes-events.png'
export { default as DIGITAL_CPHFW_UX_WRITING } from './assets/ux-ui/digital-cphfw-ux-writing.png'
export { default as DIGITAL_CPHFW_HIFI_BEFORE } from './assets/ux-ui/digital-cphfw-hifi-before.png'
export { default as DIGITAL_CPHFW_HIFI_AFTER } from './assets/ux-ui/digital-cphfw-hifi-after.png'
export { default as YOGA_PERSONA_PHOTO } from './assets/ux-ui/yoga-persona.jpg'
export { default as YOGA_CONVENTIONS } from './assets/ux-ui/yoga-conventions.png'
export { default as YOGA_UX_WRITING } from './assets/ux-ui/yoga-ux-writing.png'
